import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const packages = [
  {
    slug: "nainital",
    name: "Nainital",
    location: "Uttarakhand, India",
    image: "/packages_images/Nainital2.jpeg",
    gallery: ["/packages_images/Nainital3.jpeg", "/packages_images/Nainital4", "/packages_images/Nainital5"],
    price: "₹5,499",
    originalPrice: "₹7,499",
    discount: "27% OFF",
    duration: "3 Days / 2 Nights",
    rating: 4.7,
    reviews: 312,
    category: "Mountain",
    highlights: ["Lake Boating", "Mall Road", "Snow View"],
    groupSize: "2–12",
    featured: true,
    isSpecialOffer: false,
    isNew: false,
    bestTime: "October – June",
    description: "Nestled in the Kumaon foothills of the Himalayas, Nainital is a charming hill station wrapped around the emerald Naini Lake.",
    itinerary: [{ day: "Day 1", title: "Arrival & Lake Tour", text: "Arrive in Nainital, check in to hotel. Evening boat ride on Naini Lake." }],
    inclusions: ["2 nights hotel accommodation", "Daily breakfast & dinner", "Airport transfers"],
    exclusions: ["Travel to / from Nainital", "Lunch not included"],
  },
  {
    slug: "jaipur",
    name: "Jaipur",
    location: "Rajasthan, India",
    image: "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=600&q=80",
    gallery: ["/packages_images/Jaipur2.jpeg", "/packages_images/Jaipur3.webp"],
    price: "₹6,000",
    originalPrice: "₹8,500",
    discount: "29% OFF",
    duration: "4 Days / 3 Nights",
    rating: 4.8,
    reviews: 489,
    category: "Heritage",
    highlights: ["Amber Fort", "Hawa Mahal", "City Palace"],
    groupSize: "2–16",
    featured: true,
    isSpecialOffer: false,
    isNew: false,
    bestTime: "November – February",
    description: "The Pink City of Jaipur is a vibrant tapestry of Rajputana heritage.",
    itinerary: [{ day: "Day 1", title: "Arrival & City Palace", text: "Arrive in Jaipur, check in. Visit City Palace." }],
    inclusions: ["3 nights heritage hotel stay", "Daily breakfast", "Private AC cab"],
    exclusions: ["Travel to / from Jaipur", "Monument entry fees"],
  },
  {
    slug: "kerala",
    name: "Kerala",
    location: "South India",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=600&q=80",
    gallery: ["/packages_images/Kerala2.jpeg", "/packages_images/Kerla3.webp"],
    price: "₹7,500",
    originalPrice: "₹10,000",
    discount: "25% OFF",
    duration: "5 Days / 4 Nights",
    rating: 4.9,
    reviews: 621,
    category: "Beach",
    highlights: ["Backwaters", "Munnar Hills", "Ayurveda"],
    groupSize: "2–10",
    featured: true,
    isSpecialOffer: false,
    isNew: false,
    bestTime: "September – March",
    description: "God's Own Country — Kerala — is a lush tropical paradise.",
    itinerary: [{ day: "Day 1", title: "Arrival in Kochi", text: "Arrive in Kochi, explore Fort Kochi." }],
    inclusions: ["4 nights accommodation", "Daily breakfast", "Private AC cab"],
    exclusions: ["Travel to / from Kochi", "Lunch & dinner"],
  },
  {
    slug: "ujjain",
    name: "Ujjain",
    location: "Madhya Pradesh, India",
    image: "/images/Ujjain.jpg",
    gallery: ["/packages_images/Ujjain2.jpeg", "/packages_images/ujjain3.jpeg"],
    price: "₹3,500",
    originalPrice: "₹5,000",
    discount: "30% OFF",
    duration: "2 Days / 1 Night",
    rating: 4.5,
    reviews: 198,
    category: "Pilgrimage",
    highlights: ["Mahakaleshwar", "Shipra River", "Ram Ghat"],
    groupSize: "2–20",
    featured: false,
    isSpecialOffer: true,
    isNew: false,
    bestTime: "October – March",
    description: "One of the seven sacred cities of India, Ujjain is a spiritual powerhouse.",
    itinerary: [{ day: "Day 1", title: "Arrival & Darshan", text: "Arrive in Ujjain, check in. Visit Mahakaleshwar Temple." }],
    inclusions: ["1 night hotel accommodation", "Breakfast & dinner", "Station transfers"],
    exclusions: ["Travel to / from Ujjain", "Lunch"],
  },
  {
    slug: "varanasi",
    name: "Varanasi",
    location: "Uttar Pradesh, India",
    image: "/images/Varanasi.jpg",
    gallery: ["/packages_images/varnasi2.jpeg", "/packages_images/varanasi3.jpeg"],
    price: "₹4,999",
    originalPrice: "₹7,499",
    discount: "33% OFF",
    duration: "3 Days / 2 Nights",
    rating: 4.6,
    reviews: 410,
    category: "Pilgrimage",
    highlights: ["Ganga Aarti", "Boat Ride", "Sarnath"],
    groupSize: "2–15",
    featured: true,
    isSpecialOffer: true,
    isNew: false,
    bestTime: "October – March",
    description: "The spiritual capital of India, Varanasi is one of the oldest living cities.",
    itinerary: [{ day: "Day 1", title: "Arrival & Ganga Aarti", text: "Arrive in Varanasi, check in. Evening Ganga Aarti." }],
    inclusions: ["2 nights hotel stay", "Daily breakfast", "Sunrise boat ride"],
    exclusions: ["Travel to / from Varanasi", "Lunch & dinner"],
  },
  {
    slug: "northeast-india",
    name: "Northeast India",
    location: "Seven Sisters, India",
    image: "/images/North India.jpg",
    gallery: ["/packages_images/North India2.webp", "/packages_images/North India3.jpeg"],
    price: "₹9,999",
    originalPrice: "₹12,000",
    discount: "17% OFF",
    duration: "7 Days / 6 Nights",
    rating: 4.8,
    reviews: 276,
    category: "Adventure",
    highlights: ["Kaziranga", "Tawang", "Living Root Bridge"],
    groupSize: "4–12",
    featured: false,
    isSpecialOffer: false,
    isNew: true,
    bestTime: "October – April",
    description: "The Seven Sisters of Northeast India are a land of misty mountains.",
    itinerary: [{ day: "Day 1-2", title: "Guwahati & Kaziranga", text: "Arrive in Guwahati, visit Kamakhya Temple." }],
    inclusions: ["6 nights hotel accommodation", "Daily breakfast & dinner", "All transfers"],
    exclusions: ["Flights to / from Guwahati", "Lunch"],
  },
  {
    slug: "statue-of-unity",
    name: "Statue of Unity",
    location: "Gujarat, India",
    image: "/images/Statue of Unity.jpg",
    gallery: ["/packages_images/Statue Of Unity2.jpeg", "/packages_images/Statue Of Unity3.jpeg"],
    price: "₹5,999",
    originalPrice: "₹7,999",
    discount: "25% OFF",
    duration: "2 Days / 1 Night",
    rating: 4.4,
    reviews: 345,
    category: "Heritage",
    highlights: ["Observation Deck", "Valley View", "Light Show"],
    groupSize: "2–20",
    featured: false,
    isSpecialOffer: true,
    isNew: false,
    bestTime: "October – February",
    description: "Standing 182 metres tall, the Statue of Unity is the world's tallest statue.",
    itinerary: [{ day: "Day 1", title: "Arrival & Statue Visit", text: "Arrive at Ekta Nagar, visit the Statue of Unity." }],
    inclusions: ["1 night hotel stay", "Breakfast & dinner", "Entry tickets"],
    exclusions: ["Travel to / from Ekta Nagar", "Lunch"],
  },
  {
    slug: "lakshadweep",
    name: "Lakshadweep",
    location: "Union Territory, India",
    image: "/images/Lakshdweep.jpg",
    gallery: ["/packages_images/lakashdweep2.jpeg", "/packages_images/Lakashdweep3.jpeg"],
    price: "₹22,000",
    originalPrice: "₹38,000",
    discount: "42% OFF",
    duration: "5 Days / 4 Nights",
    rating: 4.9,
    reviews: 189,
    category: "Beach",
    highlights: ["Scuba Diving", "Coral Reefs", "Island Hop"],
    groupSize: "2–8",
    featured: true,
    isSpecialOffer: false,
    isNew: false,
    bestTime: "October – May",
    description: "A pristine archipelago of 36 islands in the Arabian Sea.",
    itinerary: [{ day: "Day 1", title: "Arrival at Agatti Island", text: "Fly from Kochi to Agatti Island." }],
    inclusions: ["4 nights beach resort stay", "All meals included", "Scuba diving session"],
    exclusions: ["Travel to / from Kochi", "Extra water sports"],
  },
  {
    slug: "goa",
    name: "Goa",
    location: "West India",
    image: "/images/Goa.jpg",
    gallery: ["/packages_images/Goa2.jpeg", "/packages_images/Goa3.jpeg"],
    price: "₹6,500",
    originalPrice: "₹9,000",
    discount: "28% OFF",
    duration: "4 Days / 3 Nights",
    rating: 4.7,
    reviews: 743,
    category: "Beach",
    highlights: ["Beach Party", "Fort Aguada", "Water Sports"],
    groupSize: "2–16",
    featured: false,
    isSpecialOffer: true,
    isNew: false,
    bestTime: "November – February",
    description: "India's favourite beach destination, Goa is a sun-soaked paradise.",
    itinerary: [{ day: "Day 1", title: "Arrival & North Goa", text: "Arrive in Goa, check in. Visit Baga and Calangute beaches." }],
    inclusions: ["3 nights beachside hotel", "Daily breakfast", "Private AC cab"],
    exclusions: ["Travel to / from Goa", "Lunch & dinner"],
  },
  {
    slug: "manali",
    name: "Manali",
    location: "Himachal Pradesh, India",
    image: "/images/Manali.jpg",
    gallery: ["/packages_images/Manali2.jpeg", "/packages_images/Manali3.jpeg"],
    price: "₹7,999",
    originalPrice: "₹11,000",
    discount: "27% OFF",
    duration: "5 Days / 4 Nights",
    rating: 4.8,
    reviews: 567,
    category: "Mountain",
    highlights: ["Rohtang Pass", "Solang Valley", "River Rafting"],
    groupSize: "2–14",
    featured: false,
    isSpecialOffer: false,
    isNew: true,
    bestTime: "October – June",
    description: "A paradise in the Kullu Valley, Manali is where snow-capped peaks meet gushing rivers.",
    itinerary: [{ day: "Day 1", title: "Arrival & Mall Road", text: "Arrive in Manali, check in. Explore Mall Road." }],
    inclusions: ["4 nights hotel stay", "Daily breakfast & dinner", "All transfers"],
    exclusions: ["Travel to / from Manali", "Lunch"],
  },
  {
    slug: "rishikesh",
    name: "Rishikesh",
    location: "Uttarakhand, India",
    image: "/images/Rishikesh.jpg",
    gallery: ["/packages_images/Rishikesh.webp", "/packages_images/Rishikesh2.webp"],
    price: "₹4,500",
    originalPrice: "₹6,500",
    discount: "31% OFF",
    duration: "3 Days / 2 Nights",
    rating: 4.6,
    reviews: 398,
    category: "Adventure",
    highlights: ["River Rafting", "Bungee Jump", "Yoga Retreat"],
    groupSize: "2–18",
    featured: false,
    isSpecialOffer: true,
    isNew: false,
    bestTime: "September – November & February – May",
    description: "The Yoga Capital of the World and India's adventure sports hub.",
    itinerary: [{ day: "Day 1", title: "Arrival & Rafting", text: "Arrive in Rishikesh, check in. Afternoon river rafting." }],
    inclusions: ["2 nights camping / hotel stay", "All meals included", "River rafting session"],
    exclusions: ["Travel to / from Haridwar", "Extra adventure activities"],
  },
  {
    slug: "darjeeling",
    name: "Darjeeling",
    location: "West Bengal, India",
    image: "/packages_images/Darjling.jpeg",
    gallery: ["/packages_images/Darjling2.jpeg", "/packages_images/Darjling3.jpeg"],
    price: "₹6,999",
    originalPrice: "₹9,500",
    discount: "26% OFF",
    duration: "4 Days / 3 Nights",
    rating: 4.7,
    reviews: 432,
    category: "Mountain",
    highlights: ["Tiger Hill", "Toy Train", "Tea Gardens"],
    groupSize: "2–12",
    featured: false,
    isSpecialOffer: false,
    isNew: true,
    bestTime: "October – March",
    description: "The Queen of the Hills — Darjeeling — is a misty mountain town.",
    itinerary: [{ day: "Day 1", title: "Arrival & Mall Road", text: "Arrive at Bagdogra/NJP, transfer to Darjeeling." }],
    inclusions: ["3 nights hotel", "Daily breakfast & dinner", "Toy Train tickets"],
    exclusions: ["Travel to / from Bagdogra or NJP", "Lunch"],
  },
];

async function main() {
  console.log("🌱 Seeding database...");

  for (const pkg of packages) {
    try {
      await prisma.package.upsert({
        where: { slug: pkg.slug },
        update: {},
        create: {
          slug: pkg.slug,
          name: pkg.name,
          location: pkg.location,
          image: pkg.image,
          gallery: JSON.stringify(pkg.gallery),
          price: pkg.price,
          originalPrice: pkg.originalPrice,
          discount: pkg.discount,
          duration: pkg.duration,
          rating: pkg.rating,
          reviews: pkg.reviews,
          category: pkg.category,
          highlights: JSON.stringify(pkg.highlights),
          groupSize: pkg.groupSize,
          featured: pkg.featured,
          isSpecialOffer: pkg.isSpecialOffer,
          isNew: pkg.isNew,
          bestTime: pkg.bestTime,
          description: pkg.description,
          itinerary: JSON.stringify(pkg.itinerary),
          inclusions: JSON.stringify(pkg.inclusions),
          exclusions: JSON.stringify(pkg.exclusions),
        },
      });
      console.log(`✅ ${pkg.name}`);
    } catch (error) {
      console.error(`❌ ${pkg.name}:`, error);
    }
  }

  console.log("🎉 Seeding complete!");
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
